### ISSUE TITLE
Replace obsolete gethostbyname()

### ISSUE THREAD

**Issue by BpArCuCTeMbI** [SoleSensei/simple-tcp-chat#6]
Replace obsolete `gethostbyname()` with `getaddrinfo()`

**Comment by solesensei** [comment]
Thanks 4 that. Will do it!

**Comment by PiyushUpadhyaya** [comment]
Is it resolved? @SoleSensei

**Comment by solesensei** [comment]
@PiyushUpadhyaya @SoleSensei  replaced with https://github.com/SoleSensei/simple-tcp-chat/commit/14c5c91c44abb4f28d8981fff2bd30419e1a10ae
closing issue
